import { Alert, Linking, Pressable, StyleSheet, Text, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { useState } from "react";
import { publicApi } from "@/src/api/services";
import { AppInput, Field, PrimaryButton } from "@/src/components/Form";
import { Screen } from "@/src/components/Screen";
import { radius, spacing, useAppTheme } from "@/src/theme/theme";
import { safeErrorMessage } from "@/src/utils/format";

const open = async (url: string) => { if (await Linking.canOpenURL(url)) await Linking.openURL(url); else Alert.alert("Unable to open link"); };
export default function ContactScreen() {
  const theme = useAppTheme(); const [form, setForm] = useState({ name: "", email: "", phone: "", message: "" }); const [saving, setSaving] = useState(false);
  const send = async () => { if (!form.name.trim() || !form.email.trim() || !form.message.trim() || form.phone.replace(/\D/g, "").length !== 10) { Alert.alert("Check your details", "Enter your name, email, 10-digit phone number, and message."); return; } try { setSaving(true); await publicApi.contact({ ...form, phone: form.phone.replace(/\D/g, "") }); Alert.alert("Message sent", "Thank you. The Starry Nights team will get back to you."); setForm({ name: "", email: "", phone: "", message: "" }); } catch (error) { Alert.alert("Unable to send message", safeErrorMessage(error)); } finally { setSaving(false); } };
  return <Screen><View style={[styles.hero, { backgroundColor: theme.colors.nav }]}><Text style={styles.heroTitle}>Starry Nights Holidays</Text><Text style={styles.heroCopy}>Journey beyond the horizon…</Text></View><View style={[styles.info, { backgroundColor: theme.colors.card, borderColor: theme.colors.border }]}><Text style={[styles.heading, { color: theme.colors.text }]}>Get in touch</Text><Pressable onPress={() => void open("tel:+918847755042")} style={styles.link}><Ionicons name="call-outline" size={20} color={theme.colors.accent} /><Text style={{ color: theme.colors.text }}>+91 884 7755 042</Text></Pressable><Pressable onPress={() => void open("mailto:travelwithstarrynights@gmail.com")} style={styles.link}><Ionicons name="mail-outline" size={20} color={theme.colors.accent} /><Text style={{ color: theme.colors.text }}>travelwithstarrynights@gmail.com</Text></Pressable><Pressable onPress={() => void open("https://maps.app.goo.gl/GXgD98K8cMPDhbS69")} style={styles.link}><Ionicons name="location-outline" size={20} color={theme.colors.accent} /><Text style={{ color: theme.colors.text, flex: 1 }}>Starry Nights Tours & Adventures, HUDCO Nanded</Text></Pressable></View><Text style={[styles.heading, { color: theme.colors.text }]}>Send a message</Text><Field label="Full name"><AppInput value={form.name} onChangeText={(name) => setForm((current) => ({ ...current, name }))} /></Field><Field label="Email"><AppInput value={form.email} onChangeText={(email) => setForm((current) => ({ ...current, email }))} keyboardType="email-address" autoCapitalize="none" /></Field><Field label="Phone"><AppInput value={form.phone} onChangeText={(phone) => setForm((current) => ({ ...current, phone: phone.replace(/\D/g, "").slice(0, 10) }))} keyboardType="phone-pad" /></Field><Field label="Message"><AppInput value={form.message} onChangeText={(message) => setForm((current) => ({ ...current, message }))} multiline textAlignVertical="top" style={styles.message} /></Field><PrimaryButton title={saving ? "Sending…" : "Send message"} disabled={saving} onPress={() => void send()} /></Screen>;
}
const styles = StyleSheet.create({ hero: { padding: spacing.xl, borderRadius: radius.lg, gap: spacing.xs }, heroTitle: { color: "#fff", fontSize: 25, fontWeight: "800" }, heroCopy: { color: "#CBD5E1" }, info: { borderWidth: 1, borderRadius: radius.lg, padding: spacing.md, gap: spacing.sm }, heading: { fontSize: 20, fontWeight: "800" }, link: { flexDirection: "row", alignItems: "center", gap: spacing.sm, minHeight: 32 }, message: { minHeight: 110, paddingTop: spacing.sm } });
