import { Share, StyleSheet, Text, View } from "react-native";
import { useLocalSearchParams } from "expo-router";
import { useQuery } from "@tanstack/react-query";
import { customerApi } from "@/src/api/services";
import { PrimaryButton } from "@/src/components/Form";
import { Screen } from "@/src/components/Screen";
import { ErrorView, LoadingView } from "@/src/components/StateViews";
import { radius, spacing, useAppTheme } from "@/src/theme/theme";
import { inr, readableDate } from "@/src/utils/format";

export default function InvoiceScreen() {
  const theme = useAppTheme(); const { tourId } = useLocalSearchParams<{ tourId: string }>(); const invoice = useQuery({ queryKey: ["invoice", tourId], queryFn: () => customerApi.invoice(tourId), enabled: Boolean(tourId) });
  if (invoice.isLoading) return <Screen><LoadingView label="Preparing invoice…" /></Screen>;
  if (invoice.isError || !invoice.data) return <Screen><ErrorView retry={() => invoice.refetch()} message="The invoice is unavailable or this tour does not belong to your account." /></Screen>;
  const data = invoice.data; const text = [`Invoice ${data.invoiceNo}`, `Bill to: ${data.billTo}`, `Trip: ${data.tourType}`, `Travel date: ${readableDate(data.date)}`, `Total: ${inr(data.totalCost)}`, `Paid: ${inr(data.paidAmount)}`, `Due: ${inr(data.dueAmount)}`].join("\n");
  return <Screen><View style={[styles.paper, { backgroundColor: theme.colors.card, borderColor: theme.colors.border }]}><Text style={[styles.kicker, { color: theme.colors.accent }]}>STARRY NIGHTS · INVOICE</Text><Text style={[styles.number, { color: theme.colors.text }]}>{data.invoiceNo}</Text><View style={styles.rule} /><Text style={[styles.trip, { color: theme.colors.text }]}>{data.tourType}</Text><Text style={{ color: theme.colors.muted }}>Bill to: {data.billTo}</Text><Text style={{ color: theme.colors.muted }}>Travel date: {readableDate(data.date)} · {data.pax} travellers</Text><View style={styles.totals}><View style={styles.totalRow}><Text style={{ color: theme.colors.muted }}>Total cost</Text><Text style={[styles.totalValue, { color: theme.colors.text }]}>{inr(data.totalCost)}</Text></View><View style={styles.totalRow}><Text style={{ color: theme.colors.muted }}>Payments received</Text><Text style={[styles.totalValue, { color: theme.colors.success }]}>{inr(data.paidAmount)}</Text></View><View style={styles.totalRow}><Text style={{ color: theme.colors.muted }}>Amount due</Text><Text style={[styles.totalValue, { color: data.dueAmount > 0 ? theme.colors.accent : theme.colors.success }]}>{inr(data.dueAmount)}</Text></View></View>{data.payments.length ? <View style={styles.records}><Text style={[styles.recordsTitle, { color: theme.colors.text }]}>Paid payments</Text>{data.payments.map((payment) => <Text key={payment.id} style={{ color: theme.colors.muted }}>{readableDate(payment.paymentDate)} · {inr(payment.amount)} · {payment.mode || "Payment"}</Text>)}</View> : null}</View><PrimaryButton title="Share invoice summary" onPress={() => { void Share.share({ title: `Invoice ${data.invoiceNo}`, message: text }); }} /></Screen>;
}
const styles = StyleSheet.create({ paper: { borderWidth: 1, borderRadius: radius.lg, padding: spacing.lg, gap: spacing.sm }, kicker: { fontWeight: "900", fontSize: 12, letterSpacing: 1 }, number: { fontSize: 25, fontWeight: "800" }, rule: { height: 1, backgroundColor: "#CBD5E1" }, trip: { fontWeight: "800", fontSize: 18 }, totals: { marginTop: spacing.sm, paddingTop: spacing.md, borderTopColor: "#CBD5E1", borderTopWidth: StyleSheet.hairlineWidth, gap: spacing.xs }, totalRow: { flexDirection: "row", justifyContent: "space-between", gap: spacing.sm }, totalValue: { textAlign: "right", fontWeight: "800" }, records: { marginTop: spacing.sm, gap: 5 }, recordsTitle: { fontWeight: "800", fontSize: 16 } });
