import { ComponentProps, ReactNode } from "react";
import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { radius, spacing, useAppTheme } from "@/src/theme/theme";

export function Field({ label, children }: { label: string; children: ReactNode }) { const theme = useAppTheme(); return <View style={styles.field}><Text style={[styles.label, { color: theme.colors.text }]}>{label}</Text>{children}</View>; }
export function AppInput({ style, ...props }: ComponentProps<typeof TextInput>) { const theme = useAppTheme(); return <TextInput {...props} placeholderTextColor={theme.colors.muted} style={[styles.input, { color: theme.colors.text, backgroundColor: theme.colors.surface, borderColor: theme.colors.border }, style]} />; }
export function PrimaryButton({ title, onPress, disabled, secondary = false }: { title: string; onPress: () => void; disabled?: boolean; secondary?: boolean }) { const theme = useAppTheme(); return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={[styles.button, { backgroundColor: secondary ? theme.colors.soft : theme.colors.accent, opacity: disabled ? .55 : 1 }]}><Text style={[styles.buttonText, { color: secondary ? theme.colors.text : "#fff" }]}>{title}</Text></Pressable>; }
export function ChoiceChips({ values, selected, onChange }: { values: string[]; selected: string; onChange: (value: string) => void }) { const theme = useAppTheme(); return <View style={styles.chips}>{values.map((value) => <Pressable key={value} onPress={() => onChange(value)} style={[styles.chip, { borderColor: selected === value ? theme.colors.accent : theme.colors.border, backgroundColor: selected === value ? theme.colors.accentSoft : theme.colors.surface }]}><Text style={{ color: selected === value ? theme.colors.accentStrong : theme.colors.text }}>{value}</Text></Pressable>)}</View>; }
const styles = StyleSheet.create({ field: { gap: 6 }, label: { fontSize: 14, fontWeight: "700" }, input: { borderWidth: 1, borderRadius: radius.sm, minHeight: 48, paddingHorizontal: spacing.sm, fontSize: 16 }, button: { minHeight: 50, alignItems: "center", justifyContent: "center", borderRadius: radius.pill, paddingHorizontal: spacing.lg }, buttonText: { fontSize: 16, fontWeight: "800" }, chips: { flexDirection: "row", flexWrap: "wrap", gap: spacing.xs }, chip: { borderWidth: 1, borderRadius: radius.pill, paddingVertical: 9, paddingHorizontal: 13 } });
